services:

  llm-database:
    image: gcr.io/iptv-cluster/pgvector:v-0.0.1
    container_name: vector_db
    environment:
      POSTGRES_USER: vector_user
      POSTGRES_PASSWORD: vector_password
      POSTGRES_DB: vector_db
    ports:
      - "5433:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    healthcheck:
      test: "exit 0"

  neo4j:
    image: gcr.io/iptv-cluster/neo4j-custom/neo4j-5.24-0.0.1
    container_name: graph_db
    environment:
      - NEO4J_AUTH=graph_user/graph_password
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./volumes/neo4j/data:/data
      - ./volumes/neo4j/logs:/logs
      - ./volumes/neo4j/import:/import
      - ./volumes/neo4j/plugins:/plugins
    healthcheck:
      test: "exit 0"
