services:

  llm-database:
    image: ankane/pgvector
    container_name: vector_db
    environment:
      POSTGRES_USER: vector_user
      POSTGRES_PASSWORD: vector_password
      POSTGRES_DB: vector_db
    ports:
      - "5433:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    healthcheck:
      test: "exit 0"

  neo4j:
    image: neo4j:5.24-enterprise  # Using the official Neo4j image
    container_name: graph_db
    environment:
      - NEO4J_AUTH=graph_user/graph_password
      - NEO4J_PLUGINS=["apoc"]  # Enable APOC
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
      - NEO4J_dbms_memory_heap_initial__size=2G
      - NEO4J_dbms_memory_heap_max__size=4G
      - NEO4J_dbms_memory_pagecache_size=1G
    ports:
      - "7474:7474"  # Neo4j Browser
      - "7687:7687"  # Bolt Protocol
    volumes:
      - ./volumes/neo4j/data:/data
      - ./volumes/neo4j/logs:/logs
      - ./volumes/neo4j/import:/import
      - ./volumes/neo4j/plugins:/plugins
    healthcheck:
      test: "exit 0"

